### ISSUE TITLE
API 호출 시 Radius 값에 따른 오류 발생

### ISSUE THREAD

**Issue by seyoung755** [kyupkyup/it_non_major-frontend#2]
지도 상에서 Zoom을 많이 했을 때 Radius가 줄어들면 에러가 발생하는 듯 싶습니다.
아마 서버쪽에서 Radius 안에 음식점이 없는 경우에 대한 예외 처리가 안돼서 그런 것 같네요.
혹은 줌을 했을 때 최대 Radius를 최소 300m 정도로 해서 조금씩 늘려보는 것도 좋을 것 같습니다.
아마 100m Radius 이하 구간에서는 예외만 나올거 같은 예감이 듭니다

그 말씀해주신 배열이 초기화안되는 문제도 이 이슈가 발생하고 나서부터 계속 피드나 지도상에 마커가 남아있는 것 같네요.
우선 서버 쪽 코드로 음식점이 없는 경우에 처리 루틴을 만들어 보겠습니다~

**Comment by seyoung755** [comment]
우선 해당 범위 내에 음식점이 없는 경우에 아래와 같이 키워드만 Return 하는 걸로 수정해둬서 에러는 발생안하네요 

[
  [
    "치킨",
    "피자",
    "탕수육",
    "고기"
  ]
]

그런데 한 번 예외가 발생한 이후부터는 말씀하신 예전 음식점들이 계속 남아있는 현상이 발생하네요
서버 쪽에서는 요청 받을때마다 새 배열로 날려서 전달하는 내용은 계속 바뀌는데 받을 때 한번 이상한 값을 받으면 그 값이 계속 저장되어있는 건 아닐까요?

**Comment by kyupkyup** [comment]
확인해보겠습니당~

**Comment by kyupkyup** [comment]
![image](https://user-images.githubusercontent.com/23183045/115140790-07a77e80-a074-11eb-86f0-c4207150dd55.png)
![image](https://user-images.githubusercontent.com/23183045/115140796-12621380-a074-11eb-917f-52cadf61789d.png)

줌을 50m 이내로 땡길 경우 해당 배열 처럼 음식 데이터가 넘어와서 빈 리스트를 보여주는 경우가 있습니다~ 

해당 부분 한번 확인해주시겠어요?

키워드 리턴이 아니라 그냥 빈 배열 리턴을 하면 될 거 같습니다 ㅎㅎ

범례 5m 이내까지 거리 지정해주어서 undefined 리턴하는 버그는 해결했습니다!

**Comment by seyoung755** [comment]
넵 없을 경우 빈 배열 리턴으로 수정해서 빌드해보겠습니다~
